name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
        yarn-version: ['3.2.3']
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install Yarn
        run: corepack enable && corepack prepare yarn@${{ matrix.yarn-version }} --activate

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run nextjs lint
        run: yarn next:lint

      - name: Run hardhat lint
        run: yarn hardhat:lint
